
CREATE TABLE pets (id SERIAL PRIMARY KEY, name VARCHAR(20) NOT NULL, author_post INT REFERENCES users(id), specie VARCHAR(20) NOT NULL, age int NOT NULL, weight INT NOT NULL, gender VARCHAR(10), chip BOOLEAN NOT NULL, photo VARCHAR(255) NOT NULL, description VARCHAR (255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE users (id SERIAL PRIMARY KEY, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, rut VARCHAR(12) UNIQUE NOT NULL, email VARCHAR(100) UNIQUE NOT NULL, password VARCHAR(50) NOT NULL, photo VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, role VARCHAR(20) DEFAULT 'usuario' CHECK (role IN ('usuario', 'administrador')));


SELECT * FROM pets;
SELECT * FROM users;
